let createClient = null;
const SUPABASE_MODULE_URL = "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";

let supabase=null,currentUser=null,businessId=null,jobFilter="upcoming",documentFilter="all";
let signatureData="",sigPad=null,sigCtx=null,drawing=false;
const state={business:null,customers:[],jobs:[],documents:[],payments:[],services:[],equipment:[],expenses:[]};
const DEFAULT_SERVICES=[
 {name:"Tree Removal",description:"Tree removal",price:0,category:"Tree Service",taxable:false},
 {name:"Tree Pruning",description:"Tree pruning",price:0,category:"Tree Service",taxable:false},
 {name:"Storm Cleanup",description:"Storm cleanup",price:0,category:"Tree Service",taxable:false},
 {name:"Stump Grinding",description:"Stump grinding",price:0,category:"Tree Service",taxable:false},
 {name:"Brush Removal",description:"Brush removal",price:0,category:"Tree Service",taxable:false},
 {name:"Mulch Installation",description:"Mulch installation",price:0,category:"Landscaping",taxable:true}
];

document.addEventListener("DOMContentLoaded",init);
async function init(){bindEvents();initSignature();const url=localStorage.getItem("WESTLAKE_SUPABASE_URL"),key=localStorage.getItem("WESTLAKE_SUPABASE_ANON");if(!url||!key){showOnly("setupScreen");return}await initSupabase(url,key)}
function bindEvents(){
 on("saveSetupBtn",saveSetup);on("resetSetupBtn",resetSetup);on("resetSetupInAppBtn",resetSetup);
 on("signInBtn",signIn);on("signUpBtn",signUp);on("resetPasswordBtn",resetPassword);
 on("createBusinessBtn",createBusiness);on("joinBusinessBtn",joinBusiness);on("businessSignOutBtn",signOut);on("signOutBtn",signOut);
 document.querySelectorAll(".tab").forEach(b=>b.addEventListener("click",()=>showView(b.dataset.view)));
 document.querySelectorAll("[data-job-filter]").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll("[data-job-filter]").forEach(x=>x.classList.remove("active"));b.classList.add("active");jobFilter=b.dataset.jobFilter;renderJobs()}));
 on("dashRevenueBtn",()=>{showView("reports")});on("dashOpenInvoicesBtn",()=>{documentFilter="open-invoices";showView("documents")});on("dashPaidInvoicesBtn",()=>{documentFilter="paid-invoices";showView("documents")});on("dashOpenEstimatesBtn",()=>{documentFilter="open-estimates";showView("documents")});on("dashScheduledJobsBtn",()=>{jobFilter="scheduled";showView("jobs")});
 on("homeNewEstimateBtn",()=>{clearDocument("Estimate");showView("documents")});on("quickNewInvoiceBtn",()=>{clearDocument("Invoice");showView("documents")});on("quickNewEstimateBtn",()=>{clearDocument("Estimate");showView("documents")});on("quickNewCustomerBtn",()=>{clearCustomer();showView("customers")});on("quickRecordPaymentBtn",openPaymentPanel);
 on("clearJobBtn",clearJob);on("saveJobBtn",saveJob);on("deleteJobBtn",deleteJob);on("completeJobBtn",completeJob);on("createInvoiceFromJobBtn",createInvoiceFromJob);
 on("clearDocumentBtn",()=>{documentFilter="all";clearDocument("Invoice")});on("saveDocumentBtn",saveDocument);on("deleteDocumentBtn",deleteDocument);on("convertEstimateBtn",convertEstimate);on("scheduleJobBtn",scheduleJobFromEstimate);on("recordPaymentCurrentBtn",openPaymentPanelForCurrent);on("markPaidBtn",markCurrentPaid);on("printDocumentBtn",printCurrentDocument);on("addBlankLineBtn",()=>addLine());on("addServiceLineBtn",addServiceLine);on("clearSignatureBtn",clearSignature);
 byId("documentApplyTax").addEventListener("change",calcDocTotals);byId("documentTaxRate").addEventListener("input",calcDocTotals);byId("documentSearch").addEventListener("input",()=>{documentFilter="all";renderDocuments()});byId("documentCustomer").addEventListener("change",fillDocumentCustomer);byId("documentType").addEventListener("change",handleDocumentTypeChange);
 byId("paymentInvoice").addEventListener("change",renderPaymentSummary);on("savePaymentBtn",savePayment);
 on("clearCustomerBtn",clearCustomer);on("saveCustomerBtn",saveCustomer);on("deleteCustomerBtn",deleteCustomer);byId("customerSearch").addEventListener("input",renderCustomers);
 on("clearEquipmentBtn",clearEquipment);on("saveEquipmentBtn",saveEquipment);on("deleteEquipmentBtn",deleteEquipment);
 on("clearExpenseBtn",clearExpense);on("saveExpenseBtn",saveExpense);on("deleteExpenseBtn",deleteExpense);
 on("saveSettingsBtn",saveSettings);on("saveServiceBtn",saveService);on("deleteServiceBtn",deleteService);
 on("exportMarketingBtn",exportMarketingCSV);on("copyMarketingEmailsBtn",copyMarketingEmails);byId("exportOnlyMarketingOk").addEventListener("change",renderMarketing);
 on("exportBackupBtn",exportBackup);byId("importBackupFile").addEventListener("change",()=>alert("Backup import is manual-safe in this cloud version to avoid duplicate records."));
 byId("reportYear").addEventListener("change",renderReports);on("exportYearReportBtn",exportYearCSV);
}
function on(id,fn){const el=byId(id);if(el)el.addEventListener("click",fn)}function byId(id){return document.getElementById(id)}function showOnly(id){["setupScreen","authScreen","businessScreen","appShell"].forEach(x=>byId(x).classList.add("hidden"));byId(id).classList.remove("hidden")}function msg(id,text){byId(id).textContent=text||""}
async function saveSetup(){
 window.__westlakeAppHandledSetup=true;
 const url=val("supabaseUrl").trim(),key=val("supabaseAnonKey").trim();
 msg("setupMessage","");
 if(!url||!key){msg("setupMessage","URL and anon public key are required.");return alert("URL and anon public key are required.")}
 if(!url.startsWith("https://")||!url.includes(".supabase.co")){msg("setupMessage","Check the Supabase URL. It should look like https://your-project.supabase.co");return;}
 msg("setupMessage","Connecting to Supabase...");
 localStorage.setItem("WESTLAKE_SUPABASE_URL",url);
 localStorage.setItem("WESTLAKE_SUPABASE_ANON",key);
 await initSupabase(url,key);
}
function resetSetup(){if(confirm("Reset Supabase setup on this phone?")){localStorage.removeItem("WESTLAKE_SUPABASE_URL");localStorage.removeItem("WESTLAKE_SUPABASE_ANON");location.reload()}}
async function initSupabase(url,key){
 try{
  if(!createClient){
   msg("setupMessage","Loading Supabase library...");
   const mod = await import(SUPABASE_MODULE_URL);
   createClient = mod.createClient;
  }
  supabase=createClient(url,key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
 }catch(e){
  msg("setupMessage","Supabase library did not load. Make sure the site has internet access, then reload and try again.");
  alert("Supabase setup could not start: "+e.message);
  showOnly("setupScreen");return;
 }
 try{
  msg("setupMessage","Checking login session...");
  const {data,error}=await supabase.auth.getSession();
  if(error)throw error;
  currentUser=data.session?.user||null;
  supabase.auth.onAuthStateChange(async(_e,session)=>{currentUser=session?.user||null;if(currentUser)await afterLogin();else showOnly("authScreen")});
  if(currentUser)await afterLogin();else showOnly("authScreen");
 }catch(e){
  msg("setupMessage","Could not connect. Check that you pasted the Project URL and anon public key, not the service role key.");
  alert("Supabase connection error: "+e.message);
  showOnly("setupScreen");
 }
}
async function signIn(){msg("authMessage","Signing in...");const {error}=await supabase.auth.signInWithPassword({email:val("authEmail").trim(),password:val("authPassword")});msg("authMessage",error?error.message:"Signed in.")}
async function signUp(){msg("authMessage","Creating account...");const {error}=await supabase.auth.signUp({email:val("authEmail").trim(),password:val("authPassword")});msg("authMessage",error?error.message:"Account created. You can sign in now.")}
async function resetPassword(){const email=val("authEmail").trim();if(!email)return msg("authMessage","Enter your email first.");const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:location.href});msg("authMessage",error?error.message:"Password reset email sent.")}
async function signOut(){await supabase.auth.signOut()}
async function afterLogin(){const {data,error}=await supabase.from("business_members").select("business_id").limit(1);if(error){alert(error.message);return}if(!data||!data.length){showOnly("businessScreen");return}businessId=data[0].business_id;await loadAll();showOnly("appShell");renderAll()}
async function createBusiness(){const name=val("businessCreateName")||"Westlake Tree Experts";const {data:biz,error}=await supabase.from("businesses").insert({name,phone:"(610) 291-1176",email:"bwestlake@business.com",address:"30 Ivy Ln\nDouglassville, PA 19518",default_tax_rate:6,invoice_terms:"Payment due within 15 days.",payment_instructions:"Please make checks payable to Westlake Tree Experts."}).select().single();if(error)return msg("businessMessage",error.message);const {error:memberError}=await supabase.from("business_members").insert({business_id:biz.id,user_id:currentUser.id,role:"owner"});if(memberError)return msg("businessMessage",memberError.message);businessId=biz.id;await seedDefaults();await afterLogin()}
async function joinBusiness(){const id=val("joinBusinessId").trim();if(!id)return msg("businessMessage","Paste Business ID.");const {error}=await supabase.from("business_members").insert({business_id:id,user_id:currentUser.id,role:"member"});if(error)return msg("businessMessage",error.message);businessId=id;await afterLogin()}
async function loadAll(){await Promise.all([load("businesses","business"),load("customers"),load("jobs"),load("documents"),load("payments"),load("services"),load("equipment"),load("expenses")]);if(!state.services.length)await seedDefaults()}
async function load(table,key=table){let q=supabase.from(table).select("*");if(table==="businesses")q=q.eq("id",businessId).single();else q=q.eq("business_id",businessId).order("created_at",{ascending:false});const {data,error}=await q;if(error){console.warn(table,error.message);state[key]=table==="businesses"?null:[];return}state[key]=data||([])}
async function seedDefaults(){for(const s of DEFAULT_SERVICES){await supabase.from("services").insert({business_id:businessId,name:s.name,description:s.description,price:s.price,category:s.category,taxable:s.taxable})}await load("services")}
function renderAll(){renderOptions();renderHome();renderJobs();renderDocuments();renderCustomers();renderEquipment();renderExpenses();renderSettings();renderServices();renderHistory();renderMarketing();renderReports();renderPaymentOptions()}
function showView(id){document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));document.querySelectorAll(".tab").forEach(t=>t.classList.toggle("active",t.dataset.view===id));byId(id).classList.add("active");if(id!=="documents")documentFilter="all";renderAll()}
function renderOptions(){const cust='<option value="">None</option>'+state.customers.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join("");["jobCustomer","documentCustomer"].forEach(id=>byId(id).innerHTML=cust);byId("documentJob").innerHTML='<option value="">None</option>'+state.jobs.map(j=>`<option value="${j.id}">${esc(j.title)} - ${formatDate(j.job_date)}</option>`).join("");byId("jobEstimate").innerHTML='<option value="">None</option>'+state.documents.filter(d=>d.type==="Estimate").map(d=>`<option value="${d.id}">${esc(d.number)} - ${esc(d.customer_name||"")}</option>`).join("");byId("jobInvoice").innerHTML='<option value="">None</option>'+state.documents.filter(d=>d.type==="Invoice").map(d=>`<option value="${d.id}">${esc(d.number)} - ${esc(d.customer_name||"")}</option>`).join("");byId("servicePicker").innerHTML='<option value="">Choose service</option>'+state.services.map(s=>`<option value="${s.id}">${esc(s.name)} ${s.price?money(s.price):""}</option>`).join("")}
function renderHome(){const paid=state.documents.filter(d=>d.type==="Invoice"&&d.status==="Paid"),openInv=state.documents.filter(isOpenInvoice),paidInv=paid,openEst=state.documents.filter(isOpenEstimate),scheduled=state.jobs.filter(j=>["Scheduled","Upcoming","In Progress"].includes(j.status));const now=new Date(),yr=now.getFullYear(),mo=now.getMonth();setText("homeMonth",money(sum(paid.filter(d=>{const dt=parseLocalDate(d.doc_date);return dt&&dt.getFullYear()===yr&&dt.getMonth()===mo}),"total")));setText("homeOpenInvoices",openInv.length);setText("homePaidInvoices",paidInv.length);setText("homeOpenEstimates",openEst.length);setText("homeJobsScheduled",scheduled.length);renderHomeLists()}
function renderHomeLists(){byId("recentCustomersList").innerHTML=state.customers.slice(0,5).map(c=>`<div class="list-item"><h4>${esc(c.name)}</h4><p>Last Service: ${formatDate(lastServiceDate(c.id))||"None yet"}</p><button onclick="window.editCustomer('${c.id}')">Open</button></div>`).join("")||"<p>No customers yet.</p>";byId("recentInvoicesList").innerHTML=state.documents.filter(d=>d.type==="Invoice").slice(0,5).map(d=>`<div class="list-item"><h4>${esc(d.number)} • ${money(d.total)}</h4><p>${esc(d.customer_name||"")} • ${formatDate(d.doc_date)} • ${esc(d.status)}</p><button onclick="window.editDocument('${d.id}')">Open</button></div>`).join("")||"<p>No invoices yet.</p>";const end=addDays(7);byId("upcomingJobsList").innerHTML=state.jobs.filter(j=>(j.job_date||"")>=today()&&(j.job_date||"")<=end&&!isCompletedJob(j)).sort((a,b)=>(a.job_date||"").localeCompare(b.job_date||"")).map(j=>`<div class="list-item"><h4>${formatDate(j.job_date)}</h4><p>${esc(j.customer_name||"")} • ${esc(j.title)}</p><button onclick="window.editJob('${j.id}')">Open</button></div>`).join("")||"<p>No jobs in the next 7 days.</p>"}
function isOpenInvoice(d){return d.type==="Invoice"&&d.status!=="Paid"&&Number(d.balance_due??d.total??0)>0}function isOpenEstimate(d){return d.type==="Estimate"&&!["Approved","Accepted","Declined"].includes(d.status)}function isCompletedJob(j){return ["Completed","Complete","Cancelled"].includes(j.status)}
function clearJob(){["jobId","jobTitle","jobStart","jobEnd","jobCrew","jobLocation","jobNotes"].forEach(id=>setVal(id,""));setVal("jobDate",today());setVal("jobStatus","Scheduled");setVal("jobCustomer","");setVal("jobEstimate","");setVal("jobInvoice","")}
async function saveJob(){if(!val("jobTitle"))return alert("Job title required.");const c=state.customers.find(x=>x.id===val("jobCustomer")),est=state.documents.find(x=>x.id===val("jobEstimate")),inv=state.documents.find(x=>x.id===val("jobInvoice"));const rec={business_id:businessId,customer_id:val("jobCustomer")||est?.customer_id||inv?.customer_id||null,customer_name:c?.name||est?.customer_name||inv?.customer_name||"",estimate_id:val("jobEstimate")||null,invoice_id:val("jobInvoice")||null,title:val("jobTitle"),status:val("jobStatus"),job_date:val("jobDate"),start_time:val("jobStart")||null,end_time:val("jobEnd")||null,crew:val("jobCrew"),location:val("jobLocation"),notes:val("jobNotes")};await upsert("jobs",val("jobId"),rec);await load("jobs");clearJob();renderAll()}
function editJob(id){const j=state.jobs.find(x=>x.id===id);if(!j)return;setVal("jobId",j.id);setVal("jobCustomer",j.customer_id||"");setVal("jobEstimate",j.estimate_id||"");setVal("jobInvoice",j.invoice_id||"");setVal("jobTitle",j.title);setVal("jobStatus",j.status);setVal("jobDate",j.job_date);setVal("jobStart",j.start_time||"");setVal("jobEnd",j.end_time||"");setVal("jobCrew",j.crew||"");setVal("jobLocation",j.location||"");setVal("jobNotes",j.notes||"");showView("jobs")}
async function deleteJob(){await del("jobs",val("jobId"));await load("jobs");clearJob();renderAll()}async function completeJob(){const id=val("jobId");if(!id)return alert("Open a job first.");await supabase.from("jobs").update({status:"Completed",notes:val("jobNotes")}).eq("id",id);await load("jobs");renderAll()}
async function createInvoiceFromJob(){const j=state.jobs.find(x=>x.id===val("jobId"));if(!j)return alert("Open a job first.");const est=state.documents.find(d=>d.id===j.estimate_id);if(est){const copy={...est,type:"Invoice",status:"Draft",number:nextNumber("Invoice"),doc_date:today(),due_date:addDays(15),job_id:j.id,job_title:j.title,business_id:businessId,signature:null};delete copy.id;delete copy.created_at;await supabase.from("documents").insert(copy);await load("documents");renderAll()}else{clearDocument("Invoice");setVal("documentCustomer",j.customer_id||"");fillDocumentCustomer();setVal("documentJob",j.id);setVal("documentPropertyAddress",j.location||"");showView("documents")}}
function renderJobs(){let rows=[...state.jobs];if(jobFilter==="scheduled")rows=rows.filter(j=>["Scheduled","Upcoming","In Progress"].includes(j.status));if(jobFilter==="upcoming")rows=rows.filter(j=>(j.job_date||"")>=today()&&!isCompletedJob(j));if(jobFilter==="completed")rows=rows.filter(j=>["Completed","Complete"].includes(j.status));rows.sort((a,b)=>(a.job_date||"").localeCompare(b.job_date||""));if(jobFilter==="calendar"){const groups={};rows.forEach(j=>{groups[j.job_date||"No Date"]=groups[j.job_date||"No Date"]||[];groups[j.job_date||"No Date"].push(j)});byId("jobList").innerHTML=Object.entries(groups).map(([date,jobs])=>`<div class="list-item"><h4>${formatDate(date)||date}</h4>${jobs.map(j=>`<p>${esc(j.customer_name||"")} • ${esc(j.title)} • ${esc(j.status)}</p><button onclick="window.editJob('${j.id}')">Open</button>`).join("")}</div>`).join("")||"<p>No jobs.</p>";return}byId("jobList").innerHTML=rows.map(j=>`<div class="list-item"><h4>${esc(j.title)} <span class="pill">${esc(j.status)}</span></h4><p>${formatDate(j.job_date)} • ${esc(j.customer_name||"")} • ${esc(j.crew||"")}</p><p>${esc(j.location||"")}</p><button onclick="window.editJob('${j.id}')">Open</button></div>`).join("")||"<p>No jobs.</p>"}
function clearDocument(type="Invoice"){["documentId","documentNotes","documentCustomerName","documentCustomerPhone","documentCustomerEmail","documentCustomerAddress","documentPropertyAddress"].forEach(id=>setVal(id,""));setVal("documentType",type);setVal("documentStatus",type==="Estimate"?"Pending Approval":"Draft");setVal("documentCustomer","");setVal("documentJob","");setVal("documentNumber",nextNumber(type));setVal("documentDate",today());setVal("documentDue",addDays(type==="Estimate"?30:15));setVal("documentTerms",state.business?.invoice_terms||"Payment due within 15 days.");setVal("documentPaymentInstructions",state.business?.payment_instructions||"Please make checks payable to Westlake Tree Experts.");byId("lineItems").innerHTML="";addLine();byId("documentApplyTax").checked=false;setVal("documentTaxRate",state.business?.default_tax_rate||6);signatureData="";clearSignature();calcDocTotals()}
function nextNumber(type){const prefix=type==="Estimate"?"EST":"INV";let maxNum=1000;state.documents.filter(d=>d.type===type&&d.number).forEach(d=>{const m=String(d.number).match(/(\d+)$/);if(m)maxNum=Math.max(maxNum,Number(m[1]))});return `${prefix}-${maxNum+1}`}
function handleDocumentTypeChange(){if(!val("documentId")){const type=val("documentType");setVal("documentNumber",nextNumber(type));setVal("documentStatus",type==="Estimate"?"Pending Approval":"Draft");setVal("documentDue",addDays(type==="Estimate"?30:15))}}
function fillDocumentCustomer(){const c=state.customers.find(x=>x.id===val("documentCustomer"));setVal("documentCustomerName",c?.name||"");setVal("documentCustomerPhone",c?.phone||"");setVal("documentCustomerEmail",c?.email||"");setVal("documentCustomerAddress",c?.address||"");setVal("documentPropertyAddress",c?.property_address||c?.address||"")}
function addLine(desc="",amt="",serviceId="",serviceName="",category="Other",taxable=false){const row=document.createElement("div");row.className="line-item";row.dataset.serviceId=serviceId;row.dataset.serviceName=serviceName||desc;row.dataset.category=category;row.dataset.taxable=taxable?"true":"false";row.innerHTML=`<label>Description<input class="line-description" value="${attr(desc)}"></label><label>Amount<input class="line-amount" type="number" step="0.01" value="${amt}"></label><button class="danger" type="button">×</button>`;row.querySelector(".line-amount").addEventListener("input",calcDocTotals);row.querySelector("button").addEventListener("click",()=>{row.remove();calcDocTotals()});byId("lineItems").appendChild(row)}
function addServiceLine(){const s=state.services.find(x=>x.id===val("servicePicker"));if(!s)return alert("Choose service.");addLine(s.description||s.name,s.price||"",s.id,s.name,s.category||"Other",!!s.taxable);if(s.taxable)byId("documentApplyTax").checked=true;calcDocTotals()}
function getLines(){return[...document.querySelectorAll("#lineItems .line-item")].map(r=>({description:r.querySelector(".line-description").value,amount:Number(r.querySelector(".line-amount").value||0),serviceId:r.dataset.serviceId,serviceName:r.dataset.serviceName||r.querySelector(".line-description").value,category:r.dataset.category||"Other",taxable:r.dataset.taxable==="true"})).filter(x=>x.description||x.amount)}
function calcDocTotals(){const subtotal=sum(getLines(),"amount"),tax=byId("documentApplyTax").checked?subtotal*(Number(val("documentTaxRate")||0)/100):0,total=subtotal+tax;let paid=0;const d=state.documents.find(x=>x.id===val("documentId"));if(d)paid=getDocPaid(d.id);const balance=Math.max(0,total-paid);setText("documentSubtotal",money(subtotal));setText("documentTax",money(tax));setText("documentTotal",money(total));setText("documentPaid",money(paid));setText("documentBalance",money(balance));return{subtotal,tax,total,amount_paid:paid,balance_due:balance}}
async function saveDocument(){const t=calcDocTotals(),c=state.customers.find(x=>x.id===val("documentCustomer")),j=state.jobs.find(x=>x.id===val("documentJob")),type=val("documentType");let number=val("documentNumber").trim()||nextNumber(type);if(!val("documentId")&&state.documents.some(d=>d.type===type&&String(d.number).toLowerCase()===number.toLowerCase()))number=nextNumber(type);let status=val("documentStatus");if(type==="Invoice"&&t.amount_paid>0&&t.balance_due>0)status="Partial Payment";if(type==="Invoice"&&t.balance_due===0&&t.total>0)status="Paid";const rec={business_id:businessId,type,status,customer_id:val("documentCustomer")||null,customer_name:val("documentCustomerName")||c?.name||"",customer_phone:val("documentCustomerPhone")||c?.phone||"",customer_email:val("documentCustomerEmail")||c?.email||"",customer_address:val("documentCustomerAddress")||c?.address||"",property_address:val("documentPropertyAddress")||c?.property_address||"",job_id:val("documentJob")||null,job_title:j?.title||"",number,doc_date:val("documentDate"),due_date:val("documentDue"),line_items:getLines(),apply_tax:byId("documentApplyTax").checked,tax_rate:Number(val("documentTaxRate")||0),subtotal:t.subtotal,tax:t.tax,total:t.total,amount_paid:t.amount_paid,balance_due:t.balance_due,notes:val("documentNotes"),terms:val("documentTerms"),payment_instructions:val("documentPaymentInstructions"),signature:signatureData};const id=await upsert("documents",val("documentId"),rec,true);await load("documents");if(id)setVal("documentId",id);renderAll();alert(`${type} saved.`)}
function editDocument(id){const d=state.documents.find(x=>x.id===id);if(!d)return;setVal("documentId",d.id);setVal("documentType",d.type);setVal("documentStatus",d.status);setVal("documentCustomer",d.customer_id||"");setVal("documentJob",d.job_id||"");setVal("documentCustomerName",d.customer_name||"");setVal("documentCustomerPhone",d.customer_phone||"");setVal("documentCustomerEmail",d.customer_email||"");setVal("documentCustomerAddress",d.customer_address||"");setVal("documentPropertyAddress",d.property_address||"");setVal("documentNumber",d.number);setVal("documentDate",d.doc_date);setVal("documentDue",d.due_date);byId("lineItems").innerHTML="";(d.line_items||[]).forEach(i=>addLine(i.description,i.amount,i.serviceId,i.serviceName,i.category,i.taxable));byId("documentApplyTax").checked=!!d.apply_tax;setVal("documentTaxRate",d.tax_rate);setVal("documentNotes",d.notes||"");setVal("documentTerms",d.terms||state.business?.invoice_terms||"");setVal("documentPaymentInstructions",d.payment_instructions||state.business?.payment_instructions||"");signatureData=d.signature||"";restoreSignature();calcDocTotals();showView("documents")}
async function deleteDocument(){await del("documents",val("documentId"));await load("documents");clearDocument("Invoice");renderAll()}
async function convertEstimate(){const d=state.documents.find(x=>x.id===val("documentId")&&x.type==="Estimate");if(!d)return alert("Open a saved estimate first.");const copy={...d,type:"Invoice",status:"Draft",number:nextNumber("Invoice"),doc_date:today(),due_date:addDays(15),amount_paid:0,balance_due:d.total,business_id:businessId};delete copy.id;delete copy.created_at;const {data,error}=await supabase.from("documents").insert(copy).select("id").single();if(error)return alert(error.message);await load("documents");editDocument(data.id)}
async function scheduleJobFromEstimate(){const d=state.documents.find(x=>x.id===val("documentId")&&x.type==="Estimate");if(!d)return alert("Open a saved estimate first.");const date=prompt("Service date in YYYY-MM-DD format:",today());if(!date)return;const rec={business_id:businessId,customer_id:d.customer_id,customer_name:d.customer_name,estimate_id:d.id,title:d.line_items?.[0]?.description||"Scheduled Job",status:"Scheduled",job_date:date,crew:"Westlake Crew",location:d.property_address||d.customer_address,notes:`Scheduled from ${d.number}`};const {data,error}=await supabase.from("jobs").insert(rec).select("id").single();if(error)return alert(error.message);await supabase.from("documents").update({status:"Approved"}).eq("id",d.id);await loadAll();editJob(data.id);alert(`Job scheduled for ${formatDate(date)}.`)}
async function markCurrentPaid(){const d=state.documents.find(x=>x.id===val("documentId")&&x.type==="Invoice");if(!d)return alert("Open a saved invoice first.");const balance=Math.max(0,Number(d.balance_due??d.total)-getDocPaid(d.id));if(balance>0){await addPayment(d.id,balance,"Paid in full","")}await supabase.from("documents").update({status:"Paid",amount_paid:Number(d.total||0),balance_due:0}).eq("id",d.id);await loadAll();editDocument(d.id)}
function renderDocuments(){let rows=[...state.documents];const q=val("documentSearch").toLowerCase();if(q)rows=rows.filter(d=>JSON.stringify(d).toLowerCase().includes(q));if(documentFilter==="open-invoices")rows=rows.filter(isOpenInvoice);if(documentFilter==="paid-invoices")rows=rows.filter(d=>d.type==="Invoice"&&d.status==="Paid");if(documentFilter==="open-estimates")rows=rows.filter(isOpenEstimate);rows.sort((a,b)=>(b.doc_date||"").localeCompare(a.doc_date||""));const label={"open-invoices":"Open Invoices","paid-invoices":"Paid Invoices","open-estimates":"Open Estimates",all:"Invoices & Estimates"}[documentFilter]||"Invoices & Estimates";setText("documentsTitle",label);const banner=documentFilter!=="all"?`<div class="filtered-banner">Showing ${label}. <button onclick="window.clearDocumentFilter()" type="button">Show All</button></div>`:"";byId("documentList").innerHTML=banner+(rows.map(d=>{const paid=getDocPaid(d.id),bal=Math.max(0,Number(d.total||0)-paid);return`<div class="list-item"><h4>${esc(d.type)} ${esc(d.number)} <span class="pill ${String(d.status).toLowerCase().replaceAll(" ","-")}">${esc(d.status)}</span></h4><p>${esc(d.customer_name||"")} • ${formatDate(d.doc_date)} • Total: <strong>${money(d.total)}</strong></p>${d.type==="Invoice"?`<p>Paid: ${money(paid)} • Balance: ${money(bal)}</p>`:""}<div class="row-actions"><button onclick="window.editDocument('${d.id}')">Open</button><button onclick="window.printRecord('${d.id}')">PDF</button>${d.type==="Invoice"&&bal>0?`<button onclick="window.recordPaymentFor('${d.id}')">Record Payment</button>`:""}</div></div>`}).join("")||"<p>No documents.</p>")}
function clearDocumentFilter(){documentFilter="all";renderDocuments()}
function getDocPaid(id){return sum(state.payments.filter(p=>p.document_id===id),"amount")}function getDocBalance(d){return Math.max(0,Number(d.total||0)-getDocPaid(d.id))}
function renderPaymentOptions(){const invoices=state.documents.filter(d=>d.type==="Invoice"&&getDocBalance(d)>0);byId("paymentInvoice").innerHTML='<option value="">Choose invoice</option>'+invoices.map(d=>`<option value="${d.id}">${esc(d.customer_name||"No Customer")} — ${esc(d.number)} — ${money(getDocBalance(d))} due</option>`).join("");renderPaymentSummary()}
function openPaymentPanel(){showView("documents");byId("paymentPanel").classList.remove("hidden");setVal("paymentDate",today());renderPaymentOptions();byId("paymentPanel").scrollIntoView({behavior:"smooth"})}
function openPaymentPanelForCurrent(){const d=state.documents.find(x=>x.id===val("documentId")&&x.type==="Invoice");if(!d)return openPaymentPanel();openPaymentPanel();setVal("paymentInvoice",d.id);setVal("paymentAmount",getDocBalance(d));renderPaymentSummary()}
function recordPaymentFor(id){showView("documents");byId("paymentPanel").classList.remove("hidden");setVal("paymentDate",today());renderPaymentOptions();setVal("paymentInvoice",id);setVal("paymentAmount",getDocBalance(state.documents.find(d=>d.id===id)));renderPaymentSummary();byId("paymentPanel").scrollIntoView({behavior:"smooth"})}
function renderPaymentSummary(){const d=state.documents.find(x=>x.id===val("paymentInvoice"));if(!d){byId("paymentInvoiceSummary").innerHTML="";return}const paid=getDocPaid(d.id),bal=getDocBalance(d);byId("paymentInvoiceSummary").innerHTML=`${esc(d.customer_name||"No Customer")}<br>Invoice ${esc(d.number)}<br>Total: ${money(d.total)}<br>Paid: ${money(paid)}<br>Balance Due: ${money(bal)}`;if(!val("paymentAmount"))setVal("paymentAmount",bal)}
async function savePayment(){const id=val("paymentInvoice"),amount=Number(val("paymentAmount")||0);if(!id||amount<=0)return alert("Choose an invoice and enter payment amount.");await addPayment(id,amount,val("paymentMethod"),val("paymentNotes"));await loadAll();const d=state.documents.find(x=>x.id===id);if(d){const paid=getDocPaid(id),balance=Math.max(0,Number(d.total||0)-paid),status=balance<=0?"Paid":"Partial Payment";await supabase.from("documents").update({amount_paid:paid,balance_due:balance,status}).eq("id",id);await loadAll()}setVal("paymentAmount","");setVal("paymentMethod","");setVal("paymentNotes","");renderAll();alert("Payment saved.")}
async function addPayment(document_id,amount,method,notes){const d=state.documents.find(x=>x.id===document_id);const {error}=await supabase.from("payments").insert({business_id:businessId,document_id,customer_id:d?.customer_id||null,payment_date:val("paymentDate")||today(),amount,method:method||"",notes:notes||""});if(error)alert(error.message)}
function clearCustomer(){["customerId","customerName","customerPhone","customerEmail","customerAddress","customerPropertyAddress","customerNotes"].forEach(id=>setVal(id,""));byId("customerMarketingOk").checked=false}
async function saveCustomer(){if(!val("customerName"))return alert("Name required.");const rec={business_id:businessId,name:val("customerName"),phone:val("customerPhone"),email:val("customerEmail"),address:val("customerAddress"),property_address:val("customerPropertyAddress"),notes:val("customerNotes"),marketing_ok:byId("customerMarketingOk").checked};await upsert("customers",val("customerId"),rec);await load("customers");clearCustomer();renderAll()}
function editCustomer(id){const c=state.customers.find(x=>x.id===id);if(!c)return;setVal("customerId",c.id);setVal("customerName",c.name);setVal("customerPhone",c.phone);setVal("customerEmail",c.email);setVal("customerAddress",c.address);setVal("customerPropertyAddress",c.property_address||"");setVal("customerNotes",c.notes);byId("customerMarketingOk").checked=!!c.marketing_ok;showView("customers")}
async function deleteCustomer(){await del("customers",val("customerId"));await load("customers");clearCustomer();renderAll()}
function renderCustomers(){const q=val("customerSearch").toLowerCase();byId("customerList").innerHTML=state.customers.filter(c=>JSON.stringify(c).toLowerCase().includes(q)).map(c=>{const docs=state.documents.filter(d=>d.customer_id===c.id),paid=sum(docs.filter(d=>d.status==="Paid"),"total");return`<div class="list-item"><h4>${esc(c.name)}</h4><p>${esc(c.phone||"")} ${esc(c.email||"")}</p><p><strong>Property:</strong> ${esc(c.property_address||"")}</p><p><strong>Last Service:</strong> ${formatDate(lastServiceDate(c.id))||"None"}</p><p><strong>Total Lifetime Revenue:</strong> ${money(paid)}</p><p>History: ${docs.length} documents • ${state.jobs.filter(j=>j.customer_id===c.id).length} jobs</p>${c.marketing_ok?'<span class="pill">Marketing OK</span>':''}<div class="row-actions"><button onclick="window.editCustomer('${c.id}')">Edit</button><button onclick="window.showCustomerHistory('${c.id}')">Customer History</button></div></div>`}).join("")||"<p>No customers.</p>"}
function lastServiceDate(customerId){const jobs=state.jobs.filter(j=>j.customer_id===customerId&&["Completed","Complete"].includes(j.status)).sort((a,b)=>(b.job_date||"").localeCompare(a.job_date||""));return jobs[0]?.job_date||""}
function showCustomerHistory(id){const c=state.customers.find(x=>x.id===id);const docs=state.documents.filter(d=>d.customer_id===id).map(d=>`${formatDate(d.doc_date)} • ${d.number} • ${d.type} • ${d.status} • ${money(d.total)}`);const jobs=state.jobs.filter(j=>j.customer_id===id).map(j=>`${formatDate(j.job_date)} • Job • ${j.status} • ${j.title}`);const pays=state.payments.filter(p=>p.customer_id===id).map(p=>`${formatDate(p.payment_date)} • Payment • ${money(p.amount)}`);alert(`${c?.name||"Customer"} History\n\n`+[...docs,...jobs,...pays].join("\n")||"No history yet.")}
function clearEquipment(){["equipmentId","equipmentName","equipmentSerial","equipmentHours","equipmentLastService","equipmentNextService","equipmentNotes"].forEach(id=>setVal(id,""))}
async function saveEquipment(){if(!val("equipmentName"))return alert("Name required.");const rec={business_id:businessId,name:val("equipmentName"),serial:val("equipmentSerial"),hours:val("equipmentHours"),last_service:val("equipmentLastService")||null,next_service:val("equipmentNextService")||null,notes:val("equipmentNotes")};await upsert("equipment",val("equipmentId"),rec);await load("equipment");clearEquipment();renderAll()}
function editEquipment(id){const e=state.equipment.find(x=>x.id===id);if(!e)return;setVal("equipmentId",e.id);setVal("equipmentName",e.name);setVal("equipmentSerial",e.serial);setVal("equipmentHours",e.hours);setVal("equipmentLastService",e.last_service);setVal("equipmentNextService",e.next_service);setVal("equipmentNotes",e.notes);showView("equipment")}
async function deleteEquipment(){await del("equipment",val("equipmentId"));await load("equipment");clearEquipment();renderAll()}function renderEquipment(){byId("equipmentList").innerHTML=state.equipment.map(e=>`<div class="list-item"><h4>${esc(e.name)}</h4><p>${esc(e.serial||"")} • Hours: ${esc(e.hours||"")}</p><p>Last: ${formatDate(e.last_service)} • Next: ${formatDate(e.next_service)}</p><button onclick="window.editEquipment('${e.id}')">Edit</button></div>`).join("")||"<p>No equipment.</p>"}
function clearExpense(){setVal("expenseId","");setVal("expenseDate",today());setVal("expenseCategory","Fuel");setVal("expenseDescription","");setVal("expenseAmount","")}async function saveExpense(){if(!val("expenseDescription"))return alert("Description required.");const rec={business_id:businessId,expense_date:val("expenseDate"),category:val("expenseCategory"),description:val("expenseDescription"),amount:Number(val("expenseAmount")||0)};await upsert("expenses",val("expenseId"),rec);await load("expenses");clearExpense();renderAll()}
function editExpense(id){const e=state.expenses.find(x=>x.id===id);if(!e)return;setVal("expenseId",e.id);setVal("expenseDate",e.expense_date);setVal("expenseCategory",e.category);setVal("expenseDescription",e.description);setVal("expenseAmount",e.amount);showView("expenses")}async function deleteExpense(){await del("expenses",val("expenseId"));await load("expenses");clearExpense();renderAll()}function renderExpenses(){byId("expenseList").innerHTML=state.expenses.map(e=>`<div class="list-item"><h4>${esc(e.description)} • ${money(e.amount)}</h4><p>${formatDate(e.expense_date)} • ${esc(e.category||"")}</p><button onclick="window.editExpense('${e.id}')">Edit</button></div>`).join("")||"<p>No expenses.</p>"}
function renderSettings(){if(!state.business)return;setText("businessIdDisplay",businessId);setVal("settingsBusinessName",state.business.name);setVal("settingsPhone",state.business.phone);setVal("settingsEmail",state.business.email);setVal("settingsAddress",state.business.address);setVal("settingsTaxRate",state.business.default_tax_rate);setVal("settingsInvoiceTerms",state.business.invoice_terms||"");setVal("settingsPaymentInstructions",state.business.payment_instructions||"")}
async function saveSettings(){const rec={name:val("settingsBusinessName"),phone:val("settingsPhone"),email:val("settingsEmail"),address:val("settingsAddress"),default_tax_rate:Number(val("settingsTaxRate")||6),invoice_terms:val("settingsInvoiceTerms"),payment_instructions:val("settingsPaymentInstructions")};await supabase.from("businesses").update(rec).eq("id",businessId);await load("businesses","business");renderAll();alert("Settings saved.")}
async function saveService(){if(!val("serviceName"))return alert("Name required.");const rec={business_id:businessId,name:val("serviceName"),description:val("serviceDescription"),price:Number(val("servicePrice")||0),category:val("serviceCategory")||"Other",taxable:byId("serviceTaxable").checked};await upsert("services",val("serviceId"),rec);await load("services");clearService();renderAll()}
function clearService(){["serviceId","serviceName","serviceDescription","servicePrice","serviceCategory"].forEach(id=>setVal(id,""));byId("serviceTaxable").checked=false}
function editService(id){const s=state.services.find(x=>x.id===id);if(!s)return;setVal("serviceId",s.id);setVal("serviceName",s.name);setVal("serviceDescription",s.description);setVal("servicePrice",s.price);setVal("serviceCategory",s.category||"");byId("serviceTaxable").checked=!!s.taxable;showView("settings")}async function deleteService(){await del("services",val("serviceId"));await load("services");clearService();renderAll()}function renderServices(){byId("serviceList").innerHTML=state.services.map(s=>`<div class="list-item"><h4>${esc(s.name)} • ${money(s.price)}</h4><p>${esc(s.category||"Other")} ${s.taxable?'<span class="pill">Taxable</span>':'<span class="pill">Non-taxable</span>'}</p><p>${esc(s.description||"")}</p><button onclick="window.editService('${s.id}')">Edit</button></div>`).join("")||"<p>No services.</p>"}
function renderHistory(){byId("historyList").innerHTML=[...state.documents,...state.jobs,...state.payments].slice(0,60).map(r=>`<div class="list-item"><h4>${esc(r.number||r.title||"Payment")}</h4><p>${esc(r.customer_name||"")} • ${formatDate(r.doc_date||r.job_date||r.payment_date)} • ${r.amount?money(r.amount):esc(r.status||"")}</p></div>`).join("")||"<p>No history.</p>"}
function renderMarketing(){const only=byId("exportOnlyMarketingOk").checked,rows=state.customers.filter(c=>c.email&&(!only||c.marketing_ok));byId("marketingList").innerHTML=rows.map(c=>`<div class="list-item"><h4>${esc(c.name)}</h4><p>${esc(c.email)}</p>${c.marketing_ok?'<span class="pill">Marketing OK</span>':''}</div>`).join("")||"<p>No contacts.</p>"}
function renderReports(){const yrs=[...new Set([new Date().getFullYear(),...state.documents.map(d=>year(d.doc_date)).filter(Boolean),...state.expenses.map(e=>year(e.expense_date)).filter(Boolean)])].sort((a,b)=>b-a),sel=byId("reportYear"),cur=sel.value||yrs[0];sel.innerHTML=yrs.map(y=>`<option value="${y}">${y}</option>`).join("");sel.value=yrs.includes(Number(cur))?cur:yrs[0];const y=Number(sel.value),invoices=state.documents.filter(d=>d.type==="Invoice"&&year(d.doc_date)===y),paid=invoices.filter(d=>d.status==="Paid"),unpaid=invoices.filter(d=>d.status!=="Paid"),exps=state.expenses.filter(e=>year(e.expense_date)===y);const revenue=sum(paid,"total"),expenseTotal=sum(exps,"amount");setText("reportRevenue",money(revenue));setText("reportOutstanding",money(sum(unpaid,"balance_due")||sum(unpaid,"total")));setText("reportExpenses",money(expenseTotal));setText("reportNet",money(revenue-expenseTotal));setText("reportTax",money(sum(paid,"tax")));setText("reportTaxable",money(sum(paid.filter(d=>d.apply_tax),"subtotal")));setText("reportNonTaxable",money(sum(paid.filter(d=>!d.apply_tax),"subtotal")));setText("reportPaidUnpaid",`${paid.length} / ${unpaid.length}`);const months=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],byMonth=Array(12).fill(0);paid.forEach(d=>{const dt=parseLocalDate(d.doc_date);if(dt)byMonth[dt.getMonth()]+=Number(d.total||0)});const max=Math.max(...byMonth,1);byId("monthlyBars").innerHTML=byMonth.map((t,i)=>`<div class="bar-row"><span>${months[i]}</span><div class="bar" style="width:${Math.max(4,t/max*100)}%"></div><strong>${money(t)}</strong></div>`).join("");const bySvc={},byCat={},byCust={};paid.forEach(d=>{byCust[d.customer_name||"Unknown"]=(byCust[d.customer_name||"Unknown"]||0)+Number(d.total||0);(d.line_items||[]).forEach(i=>{bySvc[i.serviceName||i.description||"Other"]=(bySvc[i.serviceName||i.description||"Other"]||0)+Number(i.amount||0);byCat[i.category||"Other"]=(byCat[i.category||"Other"]||0)+Number(i.amount||0)})});byId("serviceRevenueReport").innerHTML=reportRows(bySvc);byId("categoryRevenueReport").innerHTML=reportRows(byCat);byId("topCustomersReport").innerHTML=reportRows(byCust,5)}
function reportRows(obj,limit=999){const rows=Object.entries(obj).sort((a,b)=>b[1]-a[1]).slice(0,limit);return rows.map(([n,t])=>`<div class="list-item"><h4>${esc(n)}</h4><p>${money(t)}</p></div>`).join("")||"<p>No data yet.</p>"}
async function upsert(table,id,rec,returnId=false){let res;if(id)res=await supabase.from(table).update(rec).eq("id",id).select("id").single();else res=await supabase.from(table).insert(rec).select("id").single();if(res.error){alert(res.error.message);return null}return returnId?res.data?.id:null}
async function del(table,id){if(!id)return alert("No record selected.");if(!confirm("Delete this record?"))return;const {error}=await supabase.from(table).delete().eq("id",id);if(error)alert(error.message)}
function printCurrentDocument(){const d=state.documents.find(x=>x.id===val("documentId"));if(!d)return alert("Open or save a document first.");printRecord(d.id)}
function printRecord(id){
 const d=state.documents.find(x=>x.id===id),b=state.business;if(!d)return;
 const paid=getDocPaid(d.id),balance=Math.max(0,Number(d.total||0)-paid);
 const lines=(d.line_items||[]).slice(0,8).map(i=>'<tr><td>'+esc(i.description)+'</td><td>'+money(i.amount)+'</td></tr>').join('');
 const terms=d.terms?'<h3>Terms</h3><p>'+esc(d.terms).replaceAll("\n","<br>")+'</p>':'';
 const notes=d.notes?'<h3>Notes</h3><p>'+esc(d.notes).replaceAll("\n","<br>")+'</p>':'';
 const signature=d.signature?'<div class="print-avoid-break"><h3>Customer Approval</h3><img class="signature-img" src="'+d.signature+'"></div>':'<div class="print-avoid-break"><h3>Customer Approval</h3><p style="border-bottom:1px solid #333;height:24px;width:260px"></p></div>';
 byId("printArea").innerHTML=`<div class="print-document print-small"><div class="print-header print-avoid-break"><div><img class="print-logo" src="logo.png"><p><strong>${esc(b.name||"")}</strong><br>${esc(b.phone||"")}<br>${esc(b.email||"")}<br>${esc(b.address||"").replaceAll("\n","<br>")}</p></div><div class="print-title"><h2>${esc(d.type).toUpperCase()}</h2><p><strong># ${esc(d.number)}</strong><br>Date: ${formatDate(d.doc_date)}<br>Due: ${formatDate(d.due_date)}<br>Status: ${esc(d.status||"")}</p></div></div><div class="print-avoid-break"><p><strong>Customer:</strong> ${esc(d.customer_name||"")}<br>${esc(d.customer_address||"").replaceAll("\n","<br>")}<br>${esc(d.customer_phone||"")}<br>${esc(d.customer_email||"")}</p><p><strong>Property:</strong> ${esc(d.property_address||"").replaceAll("\n","<br>")}</p></div><table class="print-table"><thead><tr><th>Description</th><th>Amount</th></tr></thead><tbody>${lines}</tbody></table><div class="print-totals print-avoid-break"><div><span>Subtotal</span><strong>${money(d.subtotal)}</strong></div><div><span>Tax</span><strong>${money(d.tax)}</strong></div><div><span>Total</span><strong>${money(d.total)}</strong></div><div><span>Paid</span><strong>${money(paid)}</strong></div><div class="grand"><span>Balance Due</span><strong>${money(balance)}</strong></div></div><div class="print-payment-box print-avoid-break"><strong>Payment Information:</strong><br>${esc(d.payment_instructions||b.payment_instructions||"").replaceAll("\n","<br>")}</div>${terms}${notes}${signature}</div>`;
 setTimeout(()=>print(),100);
}
function initSignature(){sigPad=byId("signaturePad");if(!sigPad)return;sigCtx=sigPad.getContext("2d");sigCtx.lineWidth=3;sigCtx.lineCap="round";["mousedown","touchstart"].forEach(e=>sigPad.addEventListener(e,startDraw,{passive:false}));["mousemove","touchmove"].forEach(e=>sigPad.addEventListener(e,draw,{passive:false}));["mouseup","mouseleave","touchend"].forEach(e=>sigPad.addEventListener(e,endDraw,{passive:false}))}
function pos(e){const r=sigPad.getBoundingClientRect(),p=e.touches?e.touches[0]:e;return{x:(p.clientX-r.left)*(sigPad.width/r.width),y:(p.clientY-r.top)*(sigPad.height/r.height)}}function startDraw(e){e.preventDefault();drawing=true;const p=pos(e);sigCtx.beginPath();sigCtx.moveTo(p.x,p.y)}function draw(e){if(!drawing)return;e.preventDefault();const p=pos(e);sigCtx.lineTo(p.x,p.y);sigCtx.stroke()}function endDraw(){if(!drawing)return;drawing=false;signatureData=sigPad.toDataURL("image/png")}function clearSignature(){if(!sigCtx)return;sigCtx.clearRect(0,0,sigPad.width,sigPad.height);signatureData=""}function restoreSignature(){clearSignature();if(!signatureData)return;const img=new Image();img.onload=()=>sigCtx.drawImage(img,0,0,sigPad.width,sigPad.height);img.src=signatureData}
function exportMarketingCSV(){const only=byId("exportOnlyMarketingOk").checked,rows=[["FIRSTNAME","LASTNAME","EMAIL","SMS","ADDRESS","MARKETING_OK"]];state.customers.filter(c=>c.email&&(!only||c.marketing_ok)).forEach(c=>{const p=String(c.name||"").split(/\s+/),first=p.shift()||"";rows.push([first,p.join(" "),c.email||"",c.phone||"",c.address||"",c.marketing_ok?"yes":"no"])});downloadCSV("westlake-brevo-contacts.csv",rows)}
async function copyMarketingEmails(){const only=byId("exportOnlyMarketingOk").checked,emails=state.customers.filter(c=>c.email&&(!only||c.marketing_ok)).map(c=>c.email).join(", ");if(!emails)return alert("No emails.");try{await navigator.clipboard.writeText(emails);alert("Copied.")}catch{prompt("Copy emails:",emails)}}
function exportYearCSV(){const y=Number(val("reportYear")),rows=[["TYPE","DATE","NUMBER/CATEGORY","CUSTOMER/DESCRIPTION","STATUS","SUBTOTAL","TAX","TOTAL","PAID","BALANCE"]];state.documents.filter(d=>year(d.doc_date)===y).forEach(d=>rows.push([d.type,d.doc_date,d.number,d.customer_name,d.status,d.subtotal,d.tax,d.total,getDocPaid(d.id),getDocBalance(d)]));state.expenses.filter(e=>year(e.expense_date)===y).forEach(e=>rows.push(["Expense",e.expense_date,e.category,e.description,"","","",e.amount,"",""]));downloadCSV(`westlake-year-${y}.csv`,rows)}
function exportBackup(){const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="westlake-cloud-backup.json";a.click();URL.revokeObjectURL(a.href)}function downloadCSV(name,rows){const csv=rows.map(r=>r.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n"),blob=new Blob([csv],{type:"text/csv"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)}
function parseLocalDate(s){if(!s)return null;const p=String(s).split("-");if(p.length===3)return new Date(Number(p[0]),Number(p[1])-1,Number(p[2]));const d=new Date(s);return Number.isFinite(d.getTime())?d:null}function formatDate(s){const d=parseLocalDate(s);return d?d.toLocaleDateString("en-US",{month:"long",day:"numeric",year:"numeric"}):""}function sum(rows,key){return rows.reduce((s,r)=>s+Number(r[key]||0),0)}function year(d){const dt=parseLocalDate(d);return dt?dt.getFullYear():null}function today(){return new Date().toISOString().slice(0,10)}function addDays(n){const d=new Date();d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)}function money(v){return Number(v||0).toLocaleString(undefined,{style:"currency",currency:"USD"})}function val(id){return byId(id)?.value||""}function setVal(id,v){const e=byId(id);if(e)e.value=v??""}function setText(id,v){const e=byId(id);if(e)e.textContent=v}function esc(v=""){return String(v).replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[ch]))}function attr(v=""){return esc(v).replaceAll("\n"," ")}
window.editJob=editJob;window.editDocument=editDocument;window.printRecord=printRecord;window.editCustomer=editCustomer;window.editEquipment=editEquipment;window.editExpense=editExpense;window.editService=editService;window.clearDocumentFilter=clearDocumentFilter;window.recordPaymentFor=recordPaymentFor;window.showCustomerHistory=showCustomerHistory;
